version: '3.8'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: shurl
      MYSQL_USER: shurl
      MYSQL_PASSWORD: changeme
    volumes:
      - ./db/:/var/lib/mysql/

  php:
    build:
      context: ./php
    volumes:
      - ./php/app/:/var/www/symfony_docker/
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./php/app/:/var/www/symfony_docker/
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
      - db
